package main

// sdkgen_emit.go contains the TypeScript and Python client templates. Both
// are generated with the snapshot inlined as a JSON literal and evaluate
// locally with zero dependencies. The pure-JS/Pure-Python SHA-256 keeps
// bucketing identical to Go's crypto/sha256 — pinned by the conformance test.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// tsClient renders the TypeScript client.
func tsClient(snap *snapshot, raw []byte) string {
	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by switchyard sdk gen --lang typescript. DO NOT EDIT.
// Self-contained Switchyard client: zero dependencies, zero network calls.
// Snapshot: %d flags, %d segments, environment %q, protocol v%s.

export interface Clause {
  attribute: string;
  operator: string;
  values: string[];
  negate?: boolean;
}

export interface Rollout {
  kind: string;
  percentage: number;
}

export interface Rule {
  id: string;
  clauses?: Clause[];
  rollout?: Rollout;
  value?: unknown;
}

export interface FlagEnvironment {
  on: boolean;
  value?: unknown;
  rollout?: Rollout;
  rules?: Rule[];
  prerequisites?: { flag: string; variation: number }[];
}

export interface Flag {
  key: string;
  name: string;
  kind: string;
  environments: Record<string, FlagEnvironment>;
}

export interface Segment {
  key: string;
  name: string;
  rules: Rule[];
}

export interface EvalContext {
  userKey: string;
  attributes?: Record<string, string>;
}

export interface Decision {
  enabled: boolean;
  value: unknown;
  variant: string;
  reason: string;
  errorCode: string;
}

const ENV = %q;

// SWITCHYARD_SNAPSHOT: the full flag state at generation time.
const SWITCHYARD_SNAPSHOT: Record<string, unknown> = %s as Record<string, unknown>;

const FLAGS: Record<string, Flag> = (SWITCHYARD_SNAPSHOT.flags ?? {}) as Record<string, Flag>;
const SEGMENTS: Record<string, Segment> = (SWITCHYARD_SNAPSHOT.segments ?? {}) as Record<string, Segment>;

// Pure-JS SHA-256 (FIPS 180-4) so bucketing matches the Go binary exactly.
function sha256Hex(input: string): string {
  const K = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
  ];
  const rr = (x: number, n: number) => (x >>> n) | (x << (32 - n));
  let h0 = 0x6a09e667, h1 = 0xbb67ae85, h2 = 0x3c6ef372, h3 = 0xa54ff53a;
  let h4 = 0x510e527f, h5 = 0x9b05688c, h6 = 0x1f83d9ab, h7 = 0x5be0cd19;
  const bytes = new Uint8Array(input.length);
  for (let i = 0; i < input.length; i++) bytes[i] = input.charCodeAt(i) & 0xff;
  const bitLen = bytes.length * 8;
  const withPad = new Uint8Array((((bytes.length + 8) >> 6) + 1) * 64);
  withPad.set(bytes);
  withPad[bytes.length] = 0x80;
  const dv = new DataView(withPad.buffer);
  dv.setUint32(withPad.length - 4, bitLen >>> 0);
  dv.setUint32(withPad.length - 8, Math.floor(bitLen / 0x100000000));
  const w = new Uint32Array(64);
  for (let off = 0; off < withPad.length; off += 64) {
    for (let i = 0; i < 16; i++) w[i] = dv.getUint32(off + i * 4);
    for (let i = 16; i < 64; i++) {
      const s0 = rr(w[i - 15], 7) ^ rr(w[i - 15], 18) ^ (w[i - 15] >>> 3);
      const s1 = rr(w[i - 2], 17) ^ rr(w[i - 2], 19) ^ (w[i - 2] >>> 10);
      w[i] = (w[i - 16] + s0 + w[i - 7] + s1) >>> 0;
    }
    let a = h0, c = h1, d = h2, e = h3, f = h4, g = h5, hh = h6, ii = h7;
    for (let i = 0; i < 64; i++) {
      const S1 = rr(f, 6) ^ rr(f, 11) ^ rr(f, 25);
      const ch = (f & g) ^ (~f & hh);
      const t1 = (ii + S1 + ch + K[i] + w[i]) >>> 0;
      const S0 = rr(a, 2) ^ rr(a, 13) ^ rr(a, 22);
      const maj = (a & c) ^ (a & d) ^ (c & d);
      const t2 = (S0 + maj) >>> 0;
      ii = hh; hh = g; g = f; f = (e + t1) >>> 0;
      e = d; d = c; c = a; a = (t1 + t2) >>> 0;
    }
    h0 = (h0 + a) >>> 0; h1 = (h1 + c) >>> 0; h2 = (h2 + d) >>> 0; h3 = (h3 + e) >>> 0;
    h4 = (h4 + f) >>> 0; h5 = (h5 + g) >>> 0; h6 = (h6 + hh) >>> 0; h7 = (h7 + ii) >>> 0;
  }
  const out = [h0, h1, h2, h3, h4, h5, h6, h7]
    .map((x) => x.toString(16).padStart(8, "0"))
    .join("");
  return out;
}

// bucket maps (flagKey, userKey) to [0, 100) — identical to Go.
// Go: binary.BigEndian.Uint64(sha256(flagKey + ":" + userKey)[:8]) mod 100.
// 2^53 precision can't hold 2^64, so split into 32-bit halves:
// (hi*2^32 + lo) mod 100 = ((hi mod 100) * 96 + (lo mod 100)) mod 100.
export function bucket(flagKey: string, userKey: string): number {
  const hex = sha256Hex(flagKey + ":" + userKey);
  const hi = parseInt(hex.slice(0, 8), 16);
  const lo = parseInt(hex.slice(8, 16), 16);
  return ((hi %% 100) * 96 + (lo %% 100)) %% 100;
}

function attrValue(c: Clause, ctx: EvalContext): string | undefined {
  if (c.attribute === "targetingKey" || c.attribute === "userKey" || c.attribute === "key") {
    return ctx.userKey === "" ? undefined : ctx.userKey;
  }
  return ctx.attributes?.[c.attribute];
}

function clauseMatches(c: Clause, ctx: EvalContext): boolean {
  let matched = clausePositive(c, ctx);
  if (c.negate) matched = !matched;
  return matched;
}

function clausePositive(c: Clause, ctx: EvalContext): boolean {
  const v = attrValue(c, ctx);
  switch (c.operator) {
    case "segmentMatch":
      return c.values.some((s) => segmentMatches(SEGMENTS[s], ctx));
    case "in":
      return v !== undefined && c.values.includes(v);
    case "startsWith":
      return v !== undefined && c.values.some((w) => v.startsWith(w));
    case "endsWith":
      return v !== undefined && c.values.some((w) => v.endsWith(w));
    case "contains":
      return v !== undefined && c.values.some((w) => v.includes(w));
    default:
      return false;
  }
}

function segmentMatches(seg: Segment | undefined, ctx: EvalContext): boolean {
  if (!seg) return false;
  return seg.rules.some((r) => r.clauses?.every((c) => clauseMatches(c, ctx)) ?? true);
}

function ruleMatches(r: Rule, flagKey: string, ctx: EvalContext): boolean {
  const clauses = r.clauses ?? [];
  if (!clauses.every((c) => clauseMatches(c, ctx))) return false;
  if (r.rollout && r.rollout.kind === "percentage") {
    return bucket(flagKey, ctx.userKey) < r.rollout.percentage;
  }
  return true;
}

function withValue(d: Decision, f: Flag, fe: FlagEnvironment): Decision {
  switch (f.kind) {
    case "boolean":
      d.value = true;
      d.variant = "on";
      return d;
    default:
      if (fe.value === undefined || fe.value === null) {
        d.errorCode = "PARSE_ERROR";
        d.value = undefined;
        return d;
      }
      d.value = fe.value;
      d.variant = "on";
      return d;
  }
}

// evaluate resolves a flag for the generation-time environment.
export function evaluate(flagKey: string, ctx: EvalContext, defaultValue?: unknown): Decision {
  // Missing flags mirror the Go evaluator's zero-value flag: off, no error.
  const f = FLAGS[flagKey] ?? { key: flagKey, name: "", kind: "boolean", environments: {} };
  const fe = f.environments[ENV];
  if (!fe || !fe.on) {
    return { enabled: false, value: false, variant: "off", reason: "off", errorCode: "" };
  }
  for (const r of fe.rules ?? []) {
    if (ruleMatches(r, flagKey, ctx)) {
      return withValue({ enabled: true, value: undefined, variant: "", reason: "rule:" + r.id, errorCode: "" }, f, fe);
    }
  }
  if (fe.rollout && fe.rollout.kind === "percentage") {
    if (bucket(flagKey, ctx.userKey) < fe.rollout.percentage) {
      return withValue({ enabled: true, value: undefined, variant: "", reason: "rollout", errorCode: "" }, f, fe);
    }
    return { enabled: false, value: false, variant: "off", reason: "rollout", errorCode: "" };
  }
  return withValue({ enabled: true, value: undefined, variant: "", reason: "fallthrough", errorCode: "" }, f, fe);
}

export class SwitchyardClient {
  boolean(key: string, defaultValue: boolean, ctx: EvalContext): boolean {
    const d = evaluate(key, ctx);
    if (d.errorCode !== "" || typeof d.value !== "boolean") return defaultValue;
    return d.value;
  }
  string(key: string, defaultValue: string, ctx: EvalContext): string {
    const d = evaluate(key, ctx);
    if (d.errorCode !== "" || typeof d.value !== "string") return defaultValue;
    return d.value;
  }
  number(key: string, defaultValue: number, ctx: EvalContext): number {
    const d = evaluate(key, ctx);
    if (d.errorCode !== "" || typeof d.value !== "number") return defaultValue;
    return d.value;
  }
  json<T = unknown>(key: string, ctx: EvalContext): T | undefined {
    const d = evaluate(key, ctx);
    if (d.errorCode !== "" || d.value === undefined) return undefined;
    return d.value as T;
  }
}

export function newClient(): SwitchyardClient {
  return new SwitchyardClient();
}
`, len(snap.Flags), len(snap.Segments), snap.Env, snap.Version, snap.Env, compactJSON(raw))
	return b.String()
}

// pyClient renders the Python client.
func pyClient(snap *snapshot, raw []byte) string {
	var b strings.Builder
	fmt.Fprintf(&b, `# Code generated by switchyard sdk gen --lang python. DO NOT EDIT.
# Self-contained Switchyard client: stdlib only, zero network calls.
# Snapshot: %d flags, %d segments, environment %q, protocol v%s.

import hashlib
import json
from typing import Any, Dict, Optional

ENV = %q

# SWITCHYARD_SNAPSHOT: the full flag state at generation time.
SWITCHYARD_SNAPSHOT: Dict[str, Any] = json.loads(r"""
%s
""")

_FLAGS = SWITCHYARD_SNAPSHOT.get("flags", {})
_SEGMENTS = SWITCHYARD_SNAPSHOT.get("segments", {})


def _bucket(flag_key: str, user_key: str) -> int:
    """Deterministic bucket in [0, 100) — identical to the Go binary."""
    digest = hashlib.sha256((flag_key + ":" + user_key).encode()).hexdigest()
    return int(digest[:16], 16) %% 100


def _attr_value(clause: Dict[str, Any], ctx: Dict[str, Any]) -> Optional[str]:
    attr = clause.get("attribute", "")
    if attr in ("targetingKey", "userKey", "key"):
        return ctx.get("userKey") or None
    return ctx.get("attributes", {}).get(attr)


def _clause_matches(clause: Dict[str, Any], ctx: Dict[str, Any]) -> bool:
    matched = _clause_positive(clause, ctx)
    if clause.get("negate"):
        matched = not matched
    return matched


def _clause_positive(clause: Dict[str, Any], ctx: Dict[str, Any]) -> bool:
    v = _attr_value(clause, ctx)
    op = clause.get("operator", "")
    values = clause.get("values", [])
    if op == "segmentMatch":
        return any(_segment_matches(_SEGMENTS.get(s), ctx) for s in values)
    if op == "in":
        return v is not None and v in values
    if op == "startsWith":
        return v is not None and any(v.startswith(w) for w in values)
    if op == "endsWith":
        return v is not None and any(v.endswith(w) for w in values)
    if op == "contains":
        return v is not None and any(w in v for w in values)
    return False


def _segment_matches(seg: Optional[Dict[str, Any]], ctx: Dict[str, Any]) -> bool:
    if not seg:
        return False
    for rule in seg.get("rules", []):
        if all(_clause_matches(c, ctx) for c in rule.get("clauses", [])):
            return True
    return False


def _rule_matches(rule: Dict[str, Any], flag_key: str, ctx: Dict[str, Any]) -> bool:
    clauses = rule.get("clauses", [])
    if not all(_clause_matches(c, ctx) for c in clauses):
        return False
    rollout = rule.get("rollout")
    if rollout and rollout.get("kind") == "percentage":
        return _bucket(flag_key, ctx.get("userKey", "")) < rollout.get("percentage", 0)
    return True


def _with_value(decision: Dict[str, Any], flag: Dict[str, Any], fe: Dict[str, Any]) -> Dict[str, Any]:
    if flag.get("kind") == "boolean":
        decision["value"] = True
        decision["variant"] = "on"
        return decision
    value = fe.get("value")
    if value is None:
        decision["errorCode"] = "PARSE_ERROR"
        decision["value"] = None
        return decision
    decision["value"] = value
    decision["variant"] = "on"
    return decision


def evaluate(flag_key: str, ctx: Dict[str, Any], default_value: Any = None) -> Dict[str, Any]:
    """Resolve a flag for the generation-time environment."""
    # Missing flags mirror the Go evaluator's zero-value flag: off, no error.
    flag = _FLAGS.get(flag_key, {"key": flag_key, "name": "", "kind": "boolean", "environments": {}})
    fe = flag.get("environments", {}).get(ENV)
    if not fe or not fe.get("on"):
        return {"enabled": False, "value": False, "variant": "off",
                "reason": "off", "errorCode": ""}
    for rule in fe.get("rules", []):
        if _rule_matches(rule, flag_key, ctx):
            return _with_value(
                {"enabled": True, "value": None, "variant": "",
                 "reason": "rule:" + rule.get("id", ""), "errorCode": ""},
                flag, fe)
    rollout = fe.get("rollout")
    if rollout and rollout.get("kind") == "percentage":
        if _bucket(flag_key, ctx.get("userKey", "")) < rollout.get("percentage", 0):
            return _with_value(
                {"enabled": True, "value": None, "variant": "",
                 "reason": "rollout", "errorCode": ""},
                flag, fe)
        return {"enabled": False, "value": False, "variant": "off",
                "reason": "rollout", "errorCode": ""}
    return _with_value(
        {"enabled": True, "value": None, "variant": "",
         "reason": "fallthrough", "errorCode": ""},
        flag, fe)


class SwitchyardClient:
    def boolean(self, key: str, default_value: bool, ctx: Dict[str, Any]) -> bool:
        d = evaluate(key, ctx)
        if d["errorCode"] or not isinstance(d["value"], bool):
            return default_value
        return d["value"]

    def string(self, key: str, default_value: str, ctx: Dict[str, Any]) -> str:
        d = evaluate(key, ctx)
        if d["errorCode"] or not isinstance(d["value"], str):
            return default_value
        return d["value"]

    def number(self, key: str, default_value: float, ctx: Dict[str, Any]) -> float:
        d = evaluate(key, ctx)
        if d["errorCode"] or not isinstance(d["value"], (int, float)):
            return default_value
        return d["value"]

    def json(self, key: str, ctx: Dict[str, Any]) -> Any:
        d = evaluate(key, ctx)
        if d["errorCode"] or d["value"] is None:
            return None
        return d["value"]


def new_client() -> SwitchyardClient:
    return SwitchyardClient()
`, len(snap.Flags), len(snap.Segments), snap.Env, snap.Version, snap.Env, string(raw))
	return b.String()
}

// compactJSON re-marshals indented JSON to one line for embedding.
func compactJSON(raw []byte) string {
	var buf bytes.Buffer
	if err := json.Compact(&buf, raw); err != nil {
		return string(raw)
	}
	return buf.String()
}
