package migrate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/switchyard/switchyard/internal/model"
)

// Report is the concrete fidelity report type.
type Report struct {
	TotalFlags       int            `json:"total_flags"`
	FullyMappedFlags int            `json:"fully_mapped_flags"`
	Score            float64        `json:"score"`
	Unmapped         []Unmapped     `json:"unmapped"`
	ByType           map[string]int `json:"by_type"`
}

// FidelityReport computes the report from a parsed source and its gaps.
// Segment-level gaps (unbounded segments) carry the segment key in Flag;
// they degrade the segment's fidelity but must not be miscounted as
// affected flags.
func FidelityReport(source []model.Project, unmapped []Unmapped) *Report {
	affected := map[string]bool{}
	byType := map[string]int{}
	flagKeys := map[string]bool{}
	for _, p := range source {
		for _, f := range p.Flags {
			flagKeys[f.Key] = true
		}
	}
	for _, u := range unmapped {
		if u.Flag != "" && flagKeys[u.Flag] {
			affected[u.Flag] = true
		}
		byType[u.Type]++
	}
	total := 0
	for _, p := range source {
		total += len(p.Flags)
	}
	r := &Report{
		TotalFlags:       total,
		FullyMappedFlags: total - len(affected),
		Unmapped:         unmapped,
		ByType:           byType,
	}
	r.computeScore()
	return r
}

// computeScore sets the Score field, fully-mapped / total, 0..1.
// Zero flags = 1.0 (nothing to lose).
func (r *Report) computeScore() {
	if r.TotalFlags == 0 {
		r.Score = 1.0
		return
	}
	r.Score = float64(r.FullyMappedFlags) / float64(r.TotalFlags)
}

// Pass reports whether the score clears the CI gate.
func (r *Report) Pass(gate float64) bool { return r.Score >= gate }

// Markdown renders the human-readable report committed at
// docs/fidelity/launchdarkly.md and generated by the CLI.
func (r *Report) Markdown() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# LaunchDarkly migration fidelity\n\n")
	fmt.Fprintf(&b, "Generated from `testdata/fixtures/launchdarkly/`. Regenerate: `switchyard migrate --from=launchdarkly --dry-run --fidelity docs/fidelity/launchdarkly.md`.\n\n")
	fmt.Fprintf(&b, "## Summary\n\n")
	fmt.Fprintf(&b, "- **Total flags:** %d\n", r.TotalFlags)
	fmt.Fprintf(&b, "- **Fully mapped:** %d\n", r.FullyMappedFlags)
	fmt.Fprintf(&b, "- **Fidelity:** %.1f%%\n", r.Score*100)
	if len(r.ByType) > 0 {
		fmt.Fprintf(&b, "\n## Gaps by type\n\n")
		fmt.Fprintf(&b, "| Type | Count |\n|---|---|\n")
		types := make([]string, 0, len(r.ByType))
		for t := range r.ByType {
			types = append(types, t)
		}
		sort.Strings(types)
		for _, t := range types {
			fmt.Fprintf(&b, "| %s | %d |\n", t, r.ByType[t])
		}
	}
	if len(r.Unmapped) > 0 {
		fmt.Fprintf(&b, "\n## Unmapped constructs\n\n")
		fmt.Fprintf(&b, "| Project | Flag | Rule | Type | Detail |\n|---|---|---|---|---|\n")
		for _, u := range r.Unmapped {
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n",
				u.Project, u.Flag, u.Rule, u.Type, u.Detail)
		}
		fmt.Fprintf(&b, "\nEvery construct above is listed, never silently dropped. Flags carrying any gap are excluded from the fully-mapped count.\n")
	}
	return b.String()
}
